# Generated by Django 3.2.10 on 2022-03-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('best', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=1)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
