# Generated by Django 3.2.10 on 2022-03-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addiction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=700)),
                ('day', models.IntegerField()),
            ],
        ),
    ]
