# Generated by Django 3.2.10 on 2022-03-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addiction', '0003_rename_wallpapers_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='end_time',
            field=models.BigIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='user',
            name='time_left',
            field=models.BigIntegerField(default=0),
        ),
    ]
