# Generated by Django 3.2.10 on 2022-03-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addiction', '0004_auto_20220305_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_left',
            field=models.BigIntegerField(default=1814400000),
        ),
    ]
