# Generated by Django 3.2.10 on 2022-03-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addiction', '0005_alter_user_time_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='end_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
