# Generated by Django 3.2.10 on 2022-03-05 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('addiction', '0007_relapse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relapse',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 5, 8, 43, 55, 766319, tzinfo=utc)),
        ),
    ]
