# Generated by Django 3.2.10 on 2022-03-05 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('addiction', '0008_alter_relapse_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relapse',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 5, 8, 45, 0, 607892, tzinfo=utc)),
        ),
    ]
