# Generated by Django 3.2.10 on 2022-03-05 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addiction', '0009_alter_relapse_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relapse',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 5)),
        ),
    ]
