# Generated by Django 3.2.10 on 2022-03-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addiction', '0010_auto_20220305_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default="Let's Go", max_length=200),
        ),
    ]
